CREATE USER <user>
WITH PASSWORD '<password>';

GRANT CONNECT ON DATABASE <database> TO <user>;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA <schema> TO <user>;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA <schema> TO <user>;